[tool.poetry]
name = "slm"
version = "0.1.0"
description = ""
authors = ["Jose Rodriguez <jose.rodriguez@travelperk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
orjson = "^3.9.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
